/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/time-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns 20 randomized time change entries on each request */
        get: operations["listTimeChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Duration: {
            hours: number;
            minutes: number;
        };
        Allocation: {
            /** @enum {string} */
            label: "IT" | "HR" | "Sales" | "Finance" | "R&D" | "Mobile Work" | "in-motion" | "Customer";
            percentage: number;
        };
        ProjectAllocation: {
            /** @enum {string} */
            label: "IT" | "HR" | "Sales" | "Finance" | "R&D";
            percentage: number;
        }[];
        WorkplaceAllocation: {
            /** @enum {string} */
            label: "Mobile Work" | "in-motion" | "Customer";
            percentage: number;
        }[];
        TimeChange: {
            id: number;
            /**
             * Format: date-time
             * @example 2025-01-30T08:12:00.000Z
             */
            start: string;
            /**
             * Format: date-time
             * @example 2025-01-30T17:05:00.000Z
             */
            end: string;
            workTime: components["schemas"]["Duration"];
            pauseTime: components["schemas"]["Duration"];
            projectAllocation: components["schemas"]["ProjectAllocation"];
            workplaceAllocation: components["schemas"]["WorkplaceAllocation"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTimeChanges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeChange"][];
                };
            };
        };
    };
}
